### ISSUE TITLE
UnboundLocalError: local variable 'logs' referenced before assignment

### ISSUE THREAD

**Issue by leedaihung** [jin10086/tensorflow-cnn-captcha-server#2]
你好，感谢你的分享🙏

但是在执行程序的时候会出现下面的错误
Traceback (most recent call last):
  File "cnn.py", line 138, in <module>
    main()
  File "cnn.py", line 134, in main
    train(df, train_idx, valid_idx, model)
  File "cnn.py", line 123, in train
    validation_steps=len(valid_idx) // valid_batch_size,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 856, in fit
    epoch_logs = copy.copy(logs)
UnboundLocalError: local variable 'logs' referenced before assignment

网上找了很多相关的信息，没能解决，无从下手，新手求助😂

**Comment by leedaihung** [comment]
原来是样本图片太少了，1000张就不报错了
